using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace ImplicitUI
{
    /// <summary>
    /// Fills an <see cref="Image"/> that keeps its own type - Sliced, Tiled or Simple - so a framed bar can be
    /// resized without stretching its borders.
    /// </summary>
    /// <remarks>
    /// <para>
    /// There are no settings on this component. It uses the Image's own <see cref="Image.fillAmount"/>,
    /// <see cref="Image.fillMethod"/> and <see cref="Image.fillOrigin"/>, which Unity only applies when the
    /// Image type is Filled, and applies them to the mesh the Image generates for its current type. Code that
    /// already animates <c>image.fillAmount</c> keeps working, and each change rebuilds vertices only, never
    /// layout.
    /// </para>
    /// <para>
    /// The fill is measured against the mesh the Image draws, so it follows <see cref="Image.preserveAspect"/>,
    /// sprite padding and borders that shrink on a small rect, like a native Filled image.
    /// </para>
    /// <para>
    /// Horizontal and Vertical fill methods are supported. With a radial method, or when the Image type is
    /// already Filled, the mesh is left as the Image generated it.
    /// </para>
    /// </remarks>
    [AddComponentMenu("UI/Implicit UI/Implicit Fill")]
    [RequireComponent(typeof(Image))]
    [DisallowMultipleComponent]
    public sealed class ImplicitFill : BaseMeshEffect
    {
        // Shared by every instance: mesh modification runs on the main thread and never re-enters, and both
        // lists are cleared before use, so nothing leaks between meshes or Play Mode sessions.
        private static readonly List<UIVertex> s_Source = new List<UIVertex>();
        private static readonly List<UIVertex> s_Clipped = new List<UIVertex>();

        /// <summary>
        /// Clips the mesh generated by the Image to its fill settings.
        /// </summary>
        /// <param name="vh">The mesh the Image generated, after any mesh modifiers above this component.</param>
        public override void ModifyMesh(VertexHelper vh)
        {
            var image = graphic as Image;
            if (!IsActive() || image == null || !AppliesTo(image))
                return;

            var amount = image.fillAmount;
            if (amount >= 1f)
                return;

            if (amount <= 0f)
            {
                vh.Clear();
                return;
            }

            s_Source.Clear();
            vh.GetUIVertexStream(s_Source);
            if (s_Source.Count == 0)
                return;

            GetCut(image, amount, s_Source, out var axis, out var limit);
            MeshClipper.ClipTriangles(s_Source, axis, limit, s_Clipped);

            vh.Clear();
            vh.AddUIVertexTriangleStream(s_Clipped);
        }

        // True when this component clips the image; false when the Image fills itself (type Filled) or the
        // fill method is not supported yet.
        internal static bool AppliesTo(Image image)
        {
            return image.type != Image.Type.Filled
                   && (image.fillMethod == Image.FillMethod.Horizontal || image.fillMethod == Image.FillMethod.Vertical);
        }

        // Keeps the side of the cut the fill grows from, expressed as Vector2.Dot(position, axis) <= limit.
        private static void GetCut(Image image, float amount, List<UIVertex> mesh, out Vector2 axis, out float limit)
        {
            var horizontal = image.fillMethod == Image.FillMethod.Horizontal;
            var direction = horizontal ? Vector2.right : Vector2.up;
            var fromMax = horizontal
                ? image.fillOrigin == (int)Image.OriginHorizontal.Right
                : image.fillOrigin == (int)Image.OriginVertical.Top;

            var min = float.MaxValue;
            var max = float.MinValue;
            for (var i = 0; i < mesh.Count; i++)
            {
                var value = Vector2.Dot(mesh[i].position, direction);
                min = Mathf.Min(min, value);
                max = Mathf.Max(max, value);
            }

            var filled = (max - min) * amount;
            axis = fromMax ? -direction : direction;
            limit = fromMax ? filled - max : min + filled;
        }
    }
}
