using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace ImplicitUI
{
    /// <summary>
    /// Fills an <see cref="Image"/> that keeps its own type - Sliced, Tiled or Simple - so a framed bar can be
    /// resized without stretching its borders.
    /// </summary>
    /// <remarks>
    /// <para>
    /// There are no settings on this component. It uses the Image's own <see cref="Image.fillAmount"/>,
    /// <see cref="Image.fillMethod"/>, <see cref="Image.fillOrigin"/> and <see cref="Image.fillClockwise"/>, which
    /// Unity only applies when the Image type is Filled, and applies them to the mesh the Image generates for its
    /// current type. Code that already animates <c>image.fillAmount</c> keeps working, and each change rebuilds
    /// vertices only, never layout.
    /// </para>
    /// <para>
    /// The fill is measured against the mesh the Image draws, so it follows <see cref="Image.preserveAspect"/>,
    /// sprite padding and borders that shrink on a small rect, like a native Filled image.
    /// </para>
    /// <para>
    /// Every fill method is supported. Radial fills match a native Filled image: the sweep is measured in the
    /// Image's normalized space, so on a rect that is not square the fill follows what the Filled type draws
    /// rather than a true screen angle. When the Image type is already Filled, the mesh is left as the Image
    /// generated it.
    /// </para>
    /// </remarks>
    [AddComponentMenu("UI/Implicit UI/Implicit Fill")]
    [RequireComponent(typeof(Image))]
    [DisallowMultipleComponent]
    public sealed class ImplicitFill : BaseMeshEffect
    {
        // Shared by every instance: mesh modification runs on the main thread and never re-enters, and every list
        // is cleared before use, so nothing leaks between meshes or Play Mode sessions.
        private static readonly List<UIVertex> s_Source = new List<UIVertex>();
        private static readonly List<UIVertex> s_Result = new List<UIVertex>();
        private static readonly List<UIVertex> s_BoxX = new List<UIVertex>();
        private static readonly List<UIVertex> s_BoxY = new List<UIVertex>();
        private static readonly List<UIVertex> s_Sector = new List<UIVertex>();

        /// <summary>
        /// Clips the mesh generated by the Image to its fill settings.
        /// </summary>
        /// <param name="vh">The mesh the Image generated, after any mesh modifiers above this component.</param>
        public override void ModifyMesh(VertexHelper vh)
        {
            var image = graphic as Image;
            if (!IsActive() || image == null || !AppliesTo(image))
                return;

            var amount = image.fillAmount;
            if (amount >= 1f)
                return;

            if (amount <= 0f)
            {
                vh.Clear();
                return;
            }

            s_Source.Clear();
            vh.GetUIVertexStream(s_Source);
            if (s_Source.Count == 0)
                return;

            GetBounds(s_Source, out var min, out var max);
            s_Result.Clear();

            switch (image.fillMethod)
            {
                case Image.FillMethod.Horizontal:
                case Image.FillMethod.Vertical:
                    ClipLinear(image, amount, min, max);
                    break;
                case Image.FillMethod.Radial90:
                    AddSector(min, max, 0f, 0f, 1f, 1f, amount, image.fillClockwise, image.fillOrigin);
                    break;
                case Image.FillMethod.Radial180:
                    ClipRadial180(min, max, amount, image.fillClockwise, image.fillOrigin);
                    break;
                case Image.FillMethod.Radial360:
                    ClipRadial360(min, max, amount, image.fillClockwise, image.fillOrigin);
                    break;
            }

            vh.Clear();
            vh.AddUIVertexTriangleStream(s_Result);
        }

        // False when the Image fills itself: with type Filled, clipping again would apply the fill twice.
        internal static bool AppliesTo(Image image)
        {
            return image.type != Image.Type.Filled;
        }

        private static void GetBounds(List<UIVertex> mesh, out Vector2 min, out Vector2 max)
        {
            min = new Vector2(float.MaxValue, float.MaxValue);
            max = new Vector2(float.MinValue, float.MinValue);
            for (var i = 0; i < mesh.Count; i++)
            {
                Vector2 position = mesh[i].position;
                min = Vector2.Min(min, position);
                max = Vector2.Max(max, position);
            }
        }

        // Keeps the side of the cut the fill grows from, expressed as Vector2.Dot(position, axis) <= limit.
        private static void ClipLinear(Image image, float amount, Vector2 min, Vector2 max)
        {
            var horizontal = image.fillMethod == Image.FillMethod.Horizontal;
            var direction = horizontal ? Vector2.right : Vector2.up;
            var fromMax = horizontal
                ? image.fillOrigin == (int)Image.OriginHorizontal.Right
                : image.fillOrigin == (int)Image.OriginVertical.Top;

            var low = Vector2.Dot(min, direction);
            var high = Vector2.Dot(max, direction);
            var filled = (high - low) * amount;

            var axis = fromMax ? -direction : direction;
            var limit = fromMax ? filled - high : low + filled;
            MeshClipper.ClipTriangles(s_Source, axis, limit, s_Result);
        }

        // Two halves meeting at the middle of the origin edge, swept one after the other - the split a native
        // Filled image uses, so the timing of the fill matches it.
        private static void ClipRadial180(Vector2 min, Vector2 max, float amount, bool clockwise, int origin)
        {
            var firstHalf = origin > 1 ? 1 : 0;
            var splitAlongX = origin == (int)Image.Origin180.Bottom || origin == (int)Image.Origin180.Top;

            for (var side = 0; side < 2; side++)
            {
                var lowHalf = splitAlongX ? side == firstHalf : side != firstHalf;
                var from = lowHalf ? 0f : 0.5f;
                var to = lowHalf ? 0.5f : 1f;
                var fill = clockwise ? amount * 2f - side : amount * 2f - (1 - side);
                var corner = (side + origin + 3) % 4;

                if (splitAlongX)
                    AddSector(min, max, from, 0f, to, 1f, fill, clockwise, corner);
                else
                    AddSector(min, max, 0f, from, 1f, to, fill, clockwise, corner);
            }
        }

        // Four quadrants around the center, swept in turn starting from the origin side.
        private static void ClipRadial360(Vector2 min, Vector2 max, float amount, bool clockwise, int origin)
        {
            for (var quadrant = 0; quadrant < 4; quadrant++)
            {
                var fromX = quadrant < 2 ? 0f : 0.5f;
                var fromY = quadrant == 0 || quadrant == 3 ? 0f : 0.5f;
                var order = (quadrant + origin) % 4;
                var fill = clockwise ? amount * 4f - order : amount * 4f - (3 - order);

                AddSector(min, max, fromX, fromY, fromX + 0.5f, fromY + 0.5f, fill, clockwise, (quadrant + 2) % 4);
            }
        }

        // Adds the part of a box that a radial sweep keeps. The box is given as fractions of the mesh bounds, its
        // pivot is one of its corners (0 bottom-left, 1 top-left, 2 top-right, 3 bottom-right), and the sweep covers
        // fill * 90 degrees measured in the box's own normalized space, as a native Filled image does.
        private static void AddSector(Vector2 min, Vector2 max, float fromX, float fromY, float toX, float toY,
            float fill, bool clockwise, int corner)
        {
            fill = Mathf.Clamp01(fill);
            if (fill <= 0f)
                return;

            var boxMin = new Vector2(Mathf.Lerp(min.x, max.x, fromX), Mathf.Lerp(min.y, max.y, fromY));
            var boxMax = new Vector2(Mathf.Lerp(min.x, max.x, toX), Mathf.Lerp(min.y, max.y, toY));
            var width = boxMax.x - boxMin.x;
            var height = boxMax.y - boxMin.y;
            if (width <= 0f || height <= 0f)
                return;

            // Only box sides inside the mesh bounds cut anything, and no box here has both sides of one axis inside.
            var box = s_Source;
            if (fromX > 0f)
                box = Clip(box, -Vector2.right, -boxMin.x, s_BoxX);
            else if (toX < 1f)
                box = Clip(box, Vector2.right, boxMax.x, s_BoxX);

            if (fromY > 0f)
                box = Clip(box, -Vector2.up, -boxMin.y, s_BoxY);
            else if (toY < 1f)
                box = Clip(box, Vector2.up, boxMax.y, s_BoxY);

            if (fill >= 1f)
            {
                s_Result.AddRange(box);
                return;
            }

            // Local u runs from the pivot along x and v along y, each 0..1 across the box. The sweep starts at the
            // u edge and keeps angle(u, v) <= fill * 90; odd corners, or a clockwise fill, start at the v edge instead.
            // That alternation is what keeps the sweep continuous from one box to the next.
            var fromVEdge = clockwise != ((corner & 1) == 1);
            var angle = (fromVEdge ? 1f - fill : fill) * 90f * Mathf.Deg2Rad;

            var right = corner == 2 || corner == 3;
            var top = corner == 1 || corner == 2;
            var pivot = new Vector2(right ? boxMax.x : boxMin.x, top ? boxMax.y : boxMin.y);
            var signX = right ? -1f : 1f;
            var signY = top ? -1f : 1f;

            // angle(u, v) <= a  <=>  v * cos(a) - u * sin(a) <= 0, rewritten in canvas units.
            var axis = new Vector2(-Mathf.Sin(angle) * signX / width, Mathf.Cos(angle) * signY / height);
            if (fromVEdge)
                axis = -axis;

            MeshClipper.ClipTriangles(box, axis, Vector2.Dot(axis, pivot), s_Sector);
            s_Result.AddRange(s_Sector);
        }

        private static List<UIVertex> Clip(List<UIVertex> triangles, Vector2 axis, float limit, List<UIVertex> result)
        {
            MeshClipper.ClipTriangles(triangles, axis, limit, result);
            return result;
        }
    }
}
